language: rust
addons:
  apt:
    packages:
      - mono-complete
	  - mono-vbnc
rust:
  - stable
env:
  - SRC_DIR=.
  - SRC_DIR=test/CSharp
script: cd $SRC_DIR && cargo build --verbose && cargo test --verbose
