[package]
name="ffigen"
version="0.0.1"
authors=["Val V"]
description="Code generation of FFI buildings for other languages to call Rust"
license="MIT"

[dependencies]
syntex_syntax = "*"
toml = "*"
libc = "*"

[lib]
name = "ffigen"
