// THIS IS AN AUTOGENERATED FILE
// DO NOT MODIFY!

extern crate ffigen;

pub extern fn foostr_marshal(p: *const u8, p2: u32) {
	let p_shadow = ffigen::marshal::cstr_to_string(p);
	super::foostr(&p_shadow, p2);
}
